//go:generate go run gen.go
package app

const (
	// Platform defined
	INSTANCE_NUMBER          = "INSTANCE_NUMBER"
	INSTANCE_TYPE            = "INSTANCE_TYPE"
	INSTANCE_ID              = "INSTANCE_ID"
	PRETTY_INSTANCE_NAME     = "CC_PRETTY_INSTANCE_NAME"
	APP_ID                   = "APP_ID"
	APP_NAME                 = "CC_APP_NAME"
	APP_HOME                 = "APP_HOME"
	APP_FOLDER               = "APP_FOLDER"
	DEPLOYMENT_ID            = "CC_DEPLOYMENT_ID"
	COMMIT_ID                = "COMMIT_ID"
	REVERSE_PROXY_IPS        = "CC_REVERSE_PROXY_IPS"
	ELASTIC_APM_SERVICE_NAME = "ELASTIC_APM_SERVICE_NAME"

	// User overrides
	TROUBLESHOOT           = "CC_TROUBLESHOOT"
	CLAMAV                 = "CC_CLAMAV"
	VARNISH_STORAGE_SIZE   = "CC_VARNISH_STORAGE_SIZE"
	DISABLE_GIT_SUBMODULES = "CC_DISABLE_GIT_SUBMODULES"

	// Go specific
	GO_PKG        = "CC_GO_PKG"
	GO_BUILD_TOOL = "CC_GO_BUILD_TOOL"
	GO_RUNDIR     = "CC_GO_RUNDIR"

	// FS bucket
	BUCKET_HOST = "BUCKET_HOST"
	FS_BUCKET   = "CC_FS_BUCKET"

	// MySQL
	MYSQL_ADDON_DB       = "MYSQL_ADDON_DB"
	MYSQL_ADDON_PASSWORD = "MYSQL_ADDON_PASSWORD"
	MYSQL_ADDON_ROLE     = "MYSQL_ADDON_ROLE"
	MYSQL_ADDON_USER     = "MYSQL_ADDON_USER"

	// ProxySQL
	ENABLE_MYSQL_PROXYSQL          = "CC_ENABLE_MYSQL_PROXYSQL"
	MYSQL_PROXYSQL_MAX_CONNECTIONS = "CC_MYSQL_PROXYSQL_MAX_CONNECTIONS"
	MYSQL_PROXYSQL_USE_TLS         = "CC_MYSQL_PROXYSQL_USE_TLS"
	MYSQL_PROXYSQL_SOCKET_PATH     = "CC_MYSQL_PROXYSQL_SOCKET_PATH"

	// PgPool
	ENABLE_PGPOOL      = "CC_ENABLE_PGPOOL"
	PGPOOL_SOCKET_PATH = "CC_PGPOOL_SOCKET_PATH"

	// Redis
	REDIS_HOST     = "REDIS_HOST"
	REDIS_PORT     = "REDIS_PORT"
	REDIS_PASSWORD = "REDIS_PASSWORD"

	// Elastic Stack
	ELASTIC_APM_SERVER_URL   = "ELASTIC_APM_SERVER_URL"
	ES_ADDON_APM_HOST        = "ES_ADDON_APM_HOST"
	ES_ADDON_APM_AUTH_TOKEN  = "ES_ADDON_APM_AUTH_TOKEN"
	ELASTIC_APM_SECRET_TOKEN = "ELASTIC_APM_SECRET_TOKEN"
	ES_ADDON_APM_USER        = "ES_ADDON_APM_USER"
	ES_ADDON_APM_PASSWORD    = "ES_ADDON_APM_PASSWORD"
	ES_ADDON_KIBANA_HOST     = "ES_ADDON_KIBANA_HOST"
	ES_ADDON_KIBANA_USER     = "ES_ADDON_KIBANA_USER"
	ES_ADDON_KIBANA_PASSWORD = "ES_ADDON_KIBANA_PASSWORD"
	ES_ADDON_URI             = "ES_ADDON_URI"
	ES_ADDON_HOST            = "ES_ADDON_HOST"
	ES_ADDON_USER            = "ES_ADDON_USER"
	ES_ADDON_PASSWORD        = "ES_ADDON_PASSWORD"
	ES_ADDON_VERSION         = "ES_ADDON_VERSION"

	// Pulsar
	ADDON_PULSAR_BINARY_URL  = "ADDON_PULSAR_BINARY_URL"
	ADDON_PULSAR_BINARY_PORT = "ADDON_PULSAR_BINARY_PORT"
	ADDON_PULSAR_HOSTNAME    = "ADDON_PULSAR_HOSTNAME"
	ADDON_PULSAR_HTTP_URL    = "ADDON_PULSAR_HTTP_URL"
	ADDON_PULSAR_HTTP_PORT   = "ADDON_PULSAR_HTTP_PORT"
	ADDON_PULSAR_NAMESPACE   = "ADDON_PULSAR_NAMESPACE"
	ADDON_PULSAR_TENANT      = "ADDON_PULSAR_TENANT"
	ADDON_PULSAR_TOKEN       = "ADDON_PULSAR_TOKEN"

	// New Relic
	NEW_RELIC_APP_NAME    = "NEW_RELIC_APP_NAME"
	NEW_RELIC_LICENSE_KEY = "NEW_RELIC_LICENSE_KEY"

	// Socks
	SOCKS_ADDON_HOST        = "SOCKS_ADDON_HOST"
	SOCKS_ADDON_PORT        = "SOCKS_ADDON_PORT"
	SOCKS_ADDON_PRIVATE_KEY = "SOCKS_ADDON_PRIVATE_KEY"

	// VPN
	VPN_ADDON_CRT   = "VPN_ADDON_CRT"
	VPN_ADDON_CACRT = "VPN_ADDON_CACRT"
	VPN_ADDON_KEY   = "VPN_ADDON_KEY"
	VPN_ADDON_HOST  = "VPN_ADDON_HOST"
	VPN_ADDON_PORT  = "VPN_ADDON_PORT"
	VPN_ADDON_TAKEY = "VPN_ADDON_TAKEY"
	VPN_TARGETS     = "VPN_TARGETS"
)
