package prometheus

const (
	PROMETHEUS_PORT             = "CC_METRICS_PROMETHEUS_PORT"
	PROMETHEUS_PATH             = "CC_METRICS_PROMETHEUS_PATH"
	PROMETHEUS_USER             = "CC_METRICS_PROMETHEUS_USER"
	PROMETHEUS_PASSWORD         = "CC_METRICS_PROMETHEUS_PASSWORD"
	PROMETHEUS_RESPONSE_TIMEOUT = "CC_METRICS_PROMETHEUS_RESPONSE_TIMEOUT"
)
