package mongodb

const (
	// MongoDB
	MONGODB_ADDON_HOST     = "MONGODB_ADDON_HOST"
	MONGODB_ADDON_PORT     = "MONGODB_ADDON_PORT"
	MONGODB_ADDON_USER     = "MONGODB_ADDON_USER"
	MONGODB_ADDON_PASSWORD = "MONGODB_ADDON_PASSWORD"
	MONGODB_ADDON_DB       = "MONGODB_ADDON_DB"
	MONGODB_ADDON_URI      = "MONGODB_ADDON_URI"
	MONGODB_ADDON_VERSION  = "MONGODB_ADDON_PASSWORD"
)
